---
abstract: 'Validate a name against terrorist lists'
author:
  - 'Binary.com <fayland@binary.com>'
build_requires:
  Test::More: 0.96
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Milla version v1.0.5, Dist::Zilla version 5.014, CPAN::Meta::Converter version 2.133380'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Data-Validate-Terrorist
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
requires:
  perl: 5.008005
resources:
  bugtracker: https://github.com/binary-com/perl-Data-Validate-Terrorist/issues
  homepage: https://github.com/binary-com/perl-Data-Validate-Terrorist
  repository: https://github.com/binary-com/perl-Data-Validate-Terrorist.git
version: 0.01
x_contributors:
  - 'Jean-Yves Sireau <jy@binary.com>'
